'use strict';
// Weekly change report: HTML (printed to PDF by the main process).
const esc = (s) => String(s ?? '').replace(/[<>&"]/g, (c) => ({ '<': '&lt;', '>': '&gt;', '&': '&amp;', '"': '&quot;' }[c]));

function reportHtml(d, { version = '' } = {}) {
  const byLP = new Map();
  d.changes.forEach((c) => {
    const k = `${c.line}|${c.part_no}`;
    if (!byLP.has(k)) byLP.set(k, []);
    byLP.get(k).push(c);
  });
  const groups = [...byLP.entries()].map(([k, list]) => {
    const [line, part] = k.split('|');
    return `<h3>Line ${esc(line)} &middot; ${esc(part)}</h3>
<table><thead><tr><th>Date/Time</th><th>Setting</th><th>From</th><th>To</th><th>Reason</th></tr></thead><tbody>
${list.map((c) => `<tr><td>${esc(c.ts.replace('T', ' '))}</td><td>${esc(c.label)}</td><td class="n">${esc(c.from)}</td><td class="n">${esc(c.to)}</td><td>${esc(c.reason || '')}</td></tr>`).join('\n')}
</tbody></table>`;
  }).join('\n');
  const reasons = Object.entries(d.reasons).map(([r, n]) => `${esc(r)}: ${n}`).join(' &nbsp;|&nbsp; ');
  return `<!doctype html><html><head><meta charset="utf-8"><title>Setup Tracker weekly change report</title><style>
@page { size: Letter; margin: 0.6in; }
body { font: 11px/1.4 "IBM Plex Sans","Segoe UI",Arial,sans-serif; color: #1c1b19; }
h1 { font-size: 20px; margin: 0 0 2px; } h2 { font-size: 14px; margin: 18px 0 6px; border-bottom: 2px solid #dc2626; padding-bottom: 3px; }
h3 { font-size: 12px; margin: 12px 0 4px; } .sub { color: #6b665c; margin-bottom: 10px; }
.kpis { display: flex; gap: 10px; margin: 10px 0; } .kpi { border: 1px solid #cfc9bc; border-radius: 6px; padding: 8px 12px; min-width: 110px; }
.kpi b { display: block; font-size: 20px; }
table { border-collapse: collapse; width: 100%; margin-bottom: 4px; page-break-inside: auto; } tr { page-break-inside: avoid; }
th, td { border: 1px solid #d8d3c7; padding: 3px 6px; text-align: left; } th { background: #f1ede4; }
td.n { font-family: "IBM Plex Mono",Consolas,monospace; } .none { color: #6b665c; font-style: italic; }
footer { margin-top: 18px; color: #8a8478; font-size: 9px; }
</style></head><body>
<h1>Weekly change report</h1>
<div class="sub">Viking Forge &middot; ${esc(d.start)} to ${esc(d.end)}</div>
<div class="kpis">
<div class="kpi"><b>${d.entries}</b>entries logged</div>
<div class="kpi"><b>${d.changes.length}</b>setting changes</div>
<div class="kpi"><b>${byLP.size}</b>line/parts changed</div>
<div class="kpi"><b>${d.drift.length}</b>open drift alerts</div></div>
${reasons ? `<div class="sub">Change reasons logged &mdash; ${reasons}</div>` : ''}
<h2>Entries per line</h2>
<table><thead><tr>${d.lines.map((l) => `<th>L${l.line}</th>`).join('')}</tr></thead><tbody><tr>${d.lines.map((l) => `<td class="n">${l.entries}</td>`).join('')}</tr></tbody></table>
<h2>Setting changes</h2>
${groups || '<p class="none">No setting changes this week.</p>'}
<h2>Setpoint drift alerts</h2>
${d.drift.length ? `<table><thead><tr><th>Line</th><th>Part</th><th>Setting</th><th>Sheet setpoint</th><th>Actual</th><th>Entries in a row</th></tr></thead><tbody>
${d.drift.map((a) => `<tr><td>${a.line}</td><td>${esc(a.part_no)}</td><td>${esc(a.label)}</td><td class="n">${esc(a.setpoint)}</td><td class="n">${esc(a.actual)}</td><td class="n">${a.streak}</td></tr>`).join('\n')}</tbody></table>` : '<p class="none">No open drift alerts.</p>'}
<footer>Generated by Setup Tracker ${esc(version)} &middot; local data only</footer>
</body></html>`;
}

module.exports = { reportHtml };
